#!/usr/bin/env bash

if [ "$USER" = "codio" ]
then
  # ensure we're in the directory of this script
  cd "${0%/*}"

  workspace_dir="/home/codio/workspace/"
  local_bin="/usr/local/bin"

  # copy scripts
  sudo cp sinatra.rb "${local_bin}/sinatra"
  sudo cp kill_ruby "${local_bin}"
  sudo cp reset_gems "${local_bin}"

  # copy initial .codio file
  cp codio_init "${workspace_dir}/.codio"
  
  # reset the gems on this box
  reset_gems

  echo ""
  echo "Everything successfully installed."
else
  echo "This script is for setting up Codio so that it can run the code examples. You can only run it on Codio."
fi
